api_platform:
    title: 'MasterCook REST API'
    description: 'A Symfony API.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        versions: [3]
    patch_formats:
        json: ['application/json']
    eager_loading:
        force_eager: false
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    collection:
        pagination:
            enabled: false