framework:
    enabled_locales: ['fr', 'en','it']
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
