controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    requirements:
        _locale: 'fr|en'
    prefix:
        fr: /fr
        en: /en

home_fallback:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /fr
        permanent: true
api_login_check:
    path: /api/login_check